name: Pipeline

on: push

jobs:
  building:              
    runs-on: ubuntu-latest

    steps:
      - name: Reading repo
        uses: actions/checkout@v3

      - name: Python set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Running script
        run: python hello.py
